### PR TITLE
Add hosting options to documentation.

### PR DESCRIPTION
**Pull request by mikeantonelli**
Relates to #1.

### CODE REVIEW

**Comment by garrypolley** [comment]
This is awesome, thanks for the update. 

I'm a :+1:  for the change.  We should update the release documentation to mention updating that link in the readme.  A lot of people like to copy paste.

**Comment by mikeantonelli** [comment]
@garrypolley good call, updated the release doc via https://github.com/cerner/canadarm/commit/99a5248396afe217be6817d8ca7f15fd28c723ad.

**Comment by mikeantonelli** [comment]
@garrypolley I read over the link in #18, and we may be able to update the README to reference `latest`, if we didn't want to constantly update the README with each release. 

`https://cdn.jsdelivr.net/canadarm/latest/canadarm.min.js`

See Version Aliasing @: 
https://hacks.mozilla.org/2014/03/jsdelivr-the-advanced-open-source-public-cdn/

**Comment by garrypolley** [comment]
I'm 50/50 on that. It's nice to not have to update, but then the library isn't getting cached either. I'd prefer to have the bit of work to update it so consumers can copy/paste and not have to worry about it too much. 

I'll defer to what others may want as well.

**Comment by garrypolley** [comment]
Thanks for the update. I'm going to merge this now.

**Pull request merged**
